libunittest: unittest::assertions Class Reference
unittest::assertions Class Reference
A collection of assertions.
#include <assertions.hpp>
Public Member Functions
assertions ()
Constructor.
virtual ~assertions ()
Destructor.
virtual void fail (const std::string &message) const
Throws exception testfailure with a given message.
template<typename... Args>
void fail (const std::string &assertion, const std::string &text, const Args &...args) const
Builds a fail message from the parameters passed and calls the fail(message) overload.
template<typename T , typename... Args>
void assert_true (const T &value, const Args &...message) const
Asserts that a value is true.
template<typename T , typename... Args>
void assert_false (const T &value, const Args &...message) const
Asserts that a value is false.
template<typename T , typename U , typename... Args>
void assert_equal (const T &expected, const U &actual, const Args &...message) const
Asserts that two values are equal.
template<typename T , typename U , typename... Args>
void assert_not_equal (const T &first, const U &second, const Args &...message) const
Asserts that two values are not equal.
template<typename T , typename U , typename V , typename... Args>
void assert_approx_equal (const T &expected, const U &actual, const V &eps, const Args &...message) const
Asserts that two values are approximately equal up to some epsilon. The assertions succeeds if |a - b| < epsilon.
template<typename T , typename U , typename V , typename... Args>
void assert_approx_not_equal (const T &first, const U &second, const V &eps, const Args &...message) const
Asserts that two values are not approximately equal up to some epsilon. The assertions succeeds if |a - b| < epsilon is false.
template<typename T , typename U , typename... Args>
void assert_greater (const T &first, const U &second, const Args &...message) const
Asserts that the first value is greater than the second.
template<typename T , typename U , typename... Args>
void assert_greater_equal (const T &first, const U &second, const Args &...message) const
Asserts that the first value is greater than or equal to the second.
template<typename T , typename U , typename... Args>
void assert_smaller (const T &first, const U &second, const Args &...message) const
Asserts that the first value is smaller than the second.
template<typename T , typename U , typename... Args>
void assert_smaller_equal (const T &first, const U &second, const Args &...message) const
Asserts that the first value is smaller than or equal to the second.
template<typename T , typename U , typename V , typename... Args>
void assert_in_range (const T &value, const U &lower, const V &upper, const Args &...message) const
Asserts that a value is in a given range with excluding bounds.
template<typename T , typename U , typename V , typename... Args>
void assert_not_in_range (const T &value, const U &lower, const V &upper, const Args &...message) const
Asserts that a value is not in a given range with excluding bounds.
template<typename T , typename Container , typename... Args>
void assert_in_container (const T &value, const Container &container, const Args &...message) const
Asserts that a value is in a container.
template<typename T , typename Container , typename... Args>
void assert_not_in_container (const T &value, const Container &container, const Args &...message) const
Asserts that a value is not in a container.
template<typename T , typename Container , typename U , typename... Args>
void assert_approx_in_container (const T &value, const Container &container, const U &eps, const Args &...message) const
Asserts that a value is approx. in a container up to some epsilon. The assertion succeeds if |a - b| < epsilon for at least one element.
template<typename T , typename Container , typename U , typename... Args>
void assert_approx_not_in_container (const T &value, const Container &container, const U &eps, const Args &...message) const
Asserts that a value is not approx. in a container up to some epsilon. The assertion succeeds if |a - b| < epsilon is false for all elements.
template<typename Container1 , typename Container2 , typename... Args>
void assert_equal_containers (const Container1 &expected, const Container2 &actual, const Args &...message) const
Asserts that two containers are equal.
template<typename Container1 , typename Container2 , typename... Args>
void assert_not_equal_containers (const Container1 &first, const Container2 &second, const Args &...message) const
Asserts that two containers are not equal.
template<typename Container1 , typename Container2 , typename V , typename... Args>
void assert_approx_equal_containers (const Container1 &expected, const Container2 &actual, const V &eps, const Args &...message) const
Asserts that two containers are approx. equal up to some epsilon. The assertion succeeds if |a - b| < epsilon for all pairs of elements.
template<typename Container1 , typename Container2 , typename V , typename... Args>
void assert_approx_not_equal_containers (const Container1 &expected, const Container2 &actual, const V &eps, const Args &...message) const
Asserts that two containers are not approx. equal up to some epsilon. The assertion succeeds if |a - b| < epsilon is false for at least one pair of elements.
template<typename Container , typename Functor , typename... Args>
void assert_all_of (const Container &container, Functor condition, const Args &...message) const
Asserts that all container elements match a given condition.
template<typename Container , typename Functor , typename... Args>
void assert_not_all_of (const Container &container, Functor condition, const Args &...message) const
Asserts that not all container elements match a given condition.
template<typename Container , typename Functor , typename... Args>
void assert_any_of (const Container &container, Functor condition, const Args &...message) const
Asserts that any container element matches a given condition.
template<typename Container , typename Functor , typename... Args>
void assert_none_of (const Container &container, Functor condition, const Args &...message) const
Asserts that none of the container elements match a given condition.
template<typename... Args>
void assert_regex_match (const std::string &string, const std::string &regex, const Args &...message) const
Asserts that a string matches a regular expression.
template<typename... Args>
void assert_regex_match (const std::string &string, const std::regex &regex, const Args &...message) const
Asserts that a string matches a regular expression.
template<typename... Args>
void assert_not_regex_match (const std::string &string, const std::string &regex, const Args &...message) const
Asserts that a string does not match a regular expression.
template<typename... Args>
void assert_not_regex_match (const std::string &string, const std::regex &regex, const Args &...message) const
Asserts that a string does not match a regular expression.
template<typename Exception , typename Functor , typename... Args>
void assert_throw (Functor functor, const Args &...message) const
Asserts that a functor throws Exception.
template<typename Functor , typename... Args>
void assert_no_throw (Functor functor, const Args &...message) const
Asserts that a functor does not throw any exception.
Detailed Description
A collection of assertions.
Definition at line 14 of file assertions.hpp.
Constructor & Destructor Documentation
unittest::assertions::assertions ()
Constructor.
Definition at line 6 of file assertions.cpp.
unittest::assertions::~assertions () [virtual]
Destructor.
Definition at line 10 of file assertions.cpp.
Member Function Documentation
template<typename Container , typename Functor , typename... Args> void unittest::assertions::assert_all_of (const Container & container, Functor condition, const Args &... message) const [inline]
Asserts that all container elements match a given condition.
Parameters:
container A container
condition A condition returning a boolean that can be applied to each container element
message If given, is appended to the default fail message
Definition at line 463 of file assertions.hpp.
References fail().
template<typename Container , typename Functor , typename... Args> void unittest::assertions::assert_any_of (const Container & container, Functor condition, const Args &... message) const [inline]
Asserts that any container element matches a given condition.
Parameters:
container A container
condition A condition returning a boolean that can be applied to each container element
message If given, is appended to the default fail message
Definition at line 503 of file assertions.hpp.
References fail().
template<typename T , typename U , typename V , typename... Args> void unittest::assertions::assert_approx_equal (const T & expected, const U & actual, const V & eps, const Args &... message) const [inline]
Asserts that two values are approximately equal up to some epsilon. The assertions succeeds if |a - b| < epsilon.
Parameters:
expected The expected value
actual The actual value
eps The epsilon
message If given, is appended to the default fail message
Definition at line 130 of file assertions.hpp.
References fail(), unittest::is_approx_equal(), and unittest::formatting::str().
template<typename Container1 , typename Container2 , typename V , typename... Args> void unittest::assertions::assert_approx_equal_containers (const Container1 & expected, const Container2 & actual, const V & eps, const Args &... message) const [inline]
Asserts that two containers are approx. equal up to some epsilon. The assertion succeeds if |a - b| < epsilon for all pairs of elements.
Parameters:
expected The expected container
actual The actual container
eps The epsilon
message If given, is appended to the default fail message
Definition at line 418 of file assertions.hpp.
References fail(), unittest::is_containers_approx_equal(), and unittest::formatting::str().
template<typename T , typename Container , typename U , typename... Args> void unittest::assertions::assert_approx_in_container (const T & value, const Container & container, const U & eps, const Args &... message) const [inline]
Asserts that a value is approx. in a container up to some epsilon. The assertion succeeds if |a - b| < epsilon for at least one element.
Parameters:
value A value
container A container
eps The epsilon
message If given, is appended to the default fail message
Definition at line 334 of file assertions.hpp.
References fail(), unittest::is_approx_contained(), and unittest::formatting::str().
template<typename T , typename U , typename V , typename... Args> void unittest::assertions::assert_approx_not_equal (const T & first, const U & second, const V & eps, const Args &... message) const [inline]
Asserts that two values are not approximately equal up to some epsilon. The assertions succeeds if |a - b| < epsilon is false.
Parameters:
first A value
second Another value
eps The epsilon
message If given, is appended to the default fail message
Definition at line 153 of file assertions.hpp.
References fail(), unittest::is_approx_equal(), and unittest::formatting::str().
template<typename Container1 , typename Container2 , typename V , typename... Args> void unittest::assertions::assert_approx_not_equal_containers (const Container1 & expected, const Container2 & actual, const V & eps, const Args &... message) const [inline]
Asserts that two containers are not approx. equal up to some epsilon. The assertion succeeds if |a - b| < epsilon is false for at least one pair of elements.
Parameters:
expected The expected container
actual The actual container
eps The epsilon
message If given, is appended to the default fail message
Definition at line 442 of file assertions.hpp.
References fail(), unittest::is_containers_approx_equal(), and unittest::formatting::str().
template<typename T , typename Container , typename U , typename... Args> void unittest::assertions::assert_approx_not_in_container (const T & value, const Container & container, const U & eps, const Args &... message) const [inline]
Asserts that a value is not approx. in a container up to some epsilon. The assertion succeeds if |a - b| < epsilon is false for all elements.
Parameters:
value A value
container A container
eps The epsilon
message If given, is appended to the default fail message
Definition at line 357 of file assertions.hpp.
References fail(), unittest::is_approx_contained(), and unittest::formatting::str().
template<typename T , typename U , typename... Args> void unittest::assertions::assert_equal (const T & expected, const U & actual, const Args &... message) const [inline]
Asserts that two values are equal.
Parameters:
expected The expected value
actual The actual value
message If given, is appended to the default fail message
Definition at line 89 of file assertions.hpp.
References fail(), and unittest::formatting::str().
template<typename Container1 , typename Container2 , typename... Args> void unittest::assertions::assert_equal_containers (const Container1 & expected, const Container2 & actual, const Args &... message) const [inline]
Asserts that two containers are equal.
Parameters:
expected The expected container
actual The actual container
message If given, is appended to the default fail message
Definition at line 377 of file assertions.hpp.
References fail(), and unittest::is_containers_equal().
template<typename T , typename... Args> void unittest::assertions::assert_false (const T & value, const Args &... message) const [inline]
Asserts that a value is false.
Parameters:
value A value
message If given, is appended to the default fail message
Definition at line 71 of file assertions.hpp.
References fail().
template<typename T , typename U , typename... Args> void unittest::assertions::assert_greater (const T & first, const U & second, const Args &... message) const [inline]
Asserts that the first value is greater than the second.
Parameters:
first A value
second Another value
message If given, is appended to the default fail message
Definition at line 173 of file assertions.hpp.
References fail(), and unittest::formatting::str().
template<typename T , typename U , typename... Args> void unittest::assertions::assert_greater_equal (const T & first, const U & second, const Args &... message) const [inline]
Asserts that the first value is greater than or equal to the second.
Parameters:
first A value
second Another value
message If given, is appended to the default fail message
Definition at line 192 of file assertions.hpp.
References fail(), and unittest::formatting::str().
template<typename T , typename Container , typename... Args> void unittest::assertions::assert_in_container (const T & value, const Container & container, const Args &... message) const [inline]
Asserts that a value is in a container.
Parameters:
value A value
container A container
message If given, is appended to the default fail message
Definition at line 293 of file assertions.hpp.
References fail(), unittest::is_contained(), and unittest::formatting::str().
template<typename T , typename U , typename V , typename... Args> void unittest::assertions::assert_in_range (const T & value, const U & lower, const V & upper, const Args &... message) const [inline]
Asserts that a value is in a given range with excluding bounds.
Parameters:
value A value
lower The lower bound
upper The upper bound
message If given, is appended to the default fail message
Definition at line 251 of file assertions.hpp.
References fail(), unittest::is_in_range(), and unittest::formatting::str().
template<typename Functor , typename... Args> void unittest::assertions::assert_no_throw (Functor functor, const Args &... message) const [inline]
Asserts that a functor does not throw any exception.
Parameters:
functor The functor
message If given, is appended to the default fail message
Definition at line 631 of file assertions.hpp.
References fail(), and unittest::join().
template<typename Container , typename Functor , typename... Args> void unittest::assertions::assert_none_of (const Container & container, Functor condition, const Args &... message) const [inline]
Asserts that none of the container elements match a given condition.
Parameters:
container A container
condition A condition returning a boolean that can be applied to each container element
message If given, is appended to the default fail message
Definition at line 523 of file assertions.hpp.
References fail().
template<typename Container , typename Functor , typename... Args> void unittest::assertions::assert_not_all_of (const Container & container, Functor condition, const Args &... message) const [inline]
Asserts that not all container elements match a given condition.
Parameters:
container A container
condition A condition returning a boolean that can be applied to each container element
message If given, is appended to the default fail message
Definition at line 483 of file assertions.hpp.
References fail().
template<typename T , typename U , typename... Args> void unittest::assertions::assert_not_equal (const T & first, const U & second, const Args &... message) const [inline]
Asserts that two values are not equal.
Parameters:
first A value
second Another value
message If given, is appended to the default fail message
Definition at line 108 of file assertions.hpp.
References fail(), and unittest::formatting::str().
template<typename Container1 , typename Container2 , typename... Args> void unittest::assertions::assert_not_equal_containers (const Container1 & first, const Container2 & second, const Args &... message) const [inline]
Asserts that two containers are not equal.
Parameters:
first A container
second Another container
message If given, is appended to the default fail message
Definition at line 396 of file assertions.hpp.
References fail(), and unittest::is_containers_equal().
template<typename T , typename Container , typename... Args> void unittest::assertions::assert_not_in_container (const T & value, const Container & container, const Args &... message) const [inline]
Asserts that a value is not in a container.
Parameters:
value A value
container A container
message If given, is appended to the default fail message
Definition at line 312 of file assertions.hpp.
References fail(), unittest::is_contained(), and unittest::formatting::str().
template<typename T , typename U , typename V , typename... Args> void unittest::assertions::assert_not_in_range (const T & value, const U & lower, const V & upper, const Args &... message) const [inline]
Asserts that a value is not in a given range with excluding bounds.
Parameters:
value A value
lower The lower bound
upper The upper bound
message If given, is appended to the default fail message
Definition at line 273 of file assertions.hpp.
References fail(), unittest::is_in_range(), and unittest::formatting::str().
template<typename... Args> void unittest::assertions::assert_not_regex_match (const std::string & string, const std::string & regex, const Args &... message) const [inline]
Asserts that a string does not match a regular expression.
Parameters:
string A string
regex The regular expression
message If given, is appended to the default fail message
Definition at line 574 of file assertions.hpp.
References fail(), unittest::is_regex_matched(), and unittest::formatting::str().
template<typename... Args> void unittest::assertions::assert_not_regex_match (const std::string & string, const std::regex & regex, const Args &... message) const [inline]
Asserts that a string does not match a regular expression.
Parameters:
string A string
regex The regular expression
message If given, is appended to the default fail message
Definition at line 591 of file assertions.hpp.
References fail(), unittest::is_regex_matched(), and unittest::formatting::str().
template<typename... Args> void unittest::assertions::assert_regex_match (const std::string & string, const std::string & regex, const Args &... message) const [inline]
Asserts that a string matches a regular expression.
Parameters:
string A string
regex The regular expression
message If given, is appended to the default fail message
Definition at line 540 of file assertions.hpp.
References fail(), unittest::is_regex_matched(), and unittest::formatting::str().
template<typename... Args> void unittest::assertions::assert_regex_match (const std::string & string, const std::regex & regex, const Args &... message) const [inline]
Asserts that a string matches a regular expression.
Parameters:
string A string
regex The regular expression
message If given, is appended to the default fail message
Definition at line 557 of file assertions.hpp.
References fail(), unittest::is_regex_matched(), and unittest::formatting::str().
template<typename T , typename U , typename... Args> void unittest::assertions::assert_smaller (const T & first, const U & second, const Args &... message) const [inline]
Asserts that the first value is smaller than the second.
Parameters:
first A value
second Another value
message If given, is appended to the default fail message
Definition at line 211 of file assertions.hpp.
References fail(), and unittest::formatting::str().
template<typename T , typename U , typename... Args> void unittest::assertions::assert_smaller_equal (const T & first, const U & second, const Args &... message) const [inline]
Asserts that the first value is smaller than or equal to the second.
Parameters:
first A value
second Another value
message If given, is appended to the default fail message
Definition at line 230 of file assertions.hpp.
References fail(), and unittest::formatting::str().
template<typename Exception , typename Functor , typename... Args> void unittest::assertions::assert_throw (Functor functor, const Args &... message) const [inline]
Asserts that a functor throws Exception.
Parameters:
functor The functor
message If given, is appended to the default fail message
Definition at line 609 of file assertions.hpp.
References fail(), and unittest::join().
template<typename T , typename... Args> void unittest::assertions::assert_true (const T & value, const Args &... message) const [inline]
Asserts that a value is true.
Parameters:
value A value
message If given, is appended to the default fail message
Definition at line 55 of file assertions.hpp.
References fail().
void unittest::assertions::fail (const std::string & message) const [virtual]
Throws exception testfailure with a given message.
Parameters:
message The fail message
Definition at line 14 of file assertions.cpp.
Referenced by assert_all_of(), assert_any_of(), assert_approx_equal(), assert_approx_equal_containers(), assert_approx_in_container(), assert_approx_not_equal(), assert_approx_not_equal_containers(), assert_approx_not_in_container(), assert_equal(), assert_equal_containers(), assert_false(), assert_greater(), assert_greater_equal(), assert_in_container(), assert_in_range(), assert_no_throw(), assert_none_of(), assert_not_all_of(), assert_not_equal(), assert_not_equal_containers(), assert_not_in_container(), assert_not_in_range(), assert_not_regex_match(), assert_regex_match(), assert_smaller(), assert_smaller_equal(), assert_throw(), assert_true(), and fail().
template<typename... Args> void unittest::assertions::fail (const std::string & assertion, const std::string & text, const Args &... args) const [inline]
Builds a fail message from the parameters passed and calls the fail(message) overload.
Parameters:
assertion The name of the assertion
text The assertion text
args An arbitrary number of arguments that are concatenated to a single string and are appended to the base message
Definition at line 41 of file assertions.hpp.
References fail(), unittest::join(), and unittest::formatting::make_displayed_fail_message().
The documentation for this class was generated from the following files:
assertions.hpp
assertions.cpp