libunittest: unittest::argparser Class Reference
unittest::argparser Class Reference
An argument parser.
#include <argparser.hpp>
Public Member Functions
argparser ()
Constructor.
void parse (int argc, char **argv)
Parses the arguments and assigns given values.
Detailed Description
An argument parser.
Definition at line 14 of file argparser.hpp.
Constructor & Destructor Documentation
unittest::argparser::argparser ()
Constructor.
Definition at line 37 of file argparser.cpp.
Member Function Documentation
void unittest::argparser::parse (int argc, char ** argv)
Parses the arguments and assigns given values.
Parameters:
argc The number of arguments
argv The array of arguments
Definition at line 42 of file argparser.cpp.
References unittest::userargs::failure_stop(), unittest::userargs::generate_xml(), unittest::pimplpattern< argparser >::impl_, unittest::join(), unittest::userargs::name_filter(), unittest::userargs::test_name(), unittest::userargs::verbose(), and unittest::userargs::xml_filename().
Referenced by unittest::make_default_environment().
The documentation for this class was generated from the following files:
argparser.hpp
argparser.cpp