libunittest: unittest::userargs Class Reference
unittest::userargs Class Reference
High level user arguments to control application behavior.
#include <userargs.hpp>
Public Member Functions
userargs ()
Constructor.
virtual ~userargs ()
Destructor.
virtual bool verbose () const
Returns whether the output is verbose.
virtual void verbose (bool value)
Sets whether the output is verbose.
virtual bool failure_stop () const
Returns whether to stop running after the first test fails.
virtual void failure_stop (bool value)
Sets whether to stop running after first failure.
virtual bool generate_xml () const
Returns whether to generate XML output.
virtual void generate_xml (bool value)
Sets whether to generate XML output.
virtual std::string name_filter () const
Returns a name filter on the full test name.
virtual void name_filter (const std::string &value)
Sets a name filter on the full test name.
virtual std::string test_name () const
Returns a certain test to be run. This supersedes the name filter.
virtual void test_name (const std::string &value)
Sets a certain test to be run. This supersedes the name filter.
virtual std::string xml_filename () const
Returns the XML output file name.
virtual void xml_filename (const std::string &value)
Sets the XML output file name.
Protected Attributes
bool verbose_
bool failure_stop_
bool generate_xml_
std::string name_filter_
std::string test_name_
std::string xml_filename_
Detailed Description
High level user arguments to control application behavior.
Definition at line 10 of file userargs.hpp.
Constructor & Destructor Documentation
unittest::userargs::userargs ()
Constructor.
Definition at line 5 of file userargs.cpp.
unittest::userargs::~userargs () [virtual]
Destructor.
Definition at line 10 of file userargs.cpp.
Member Function Documentation
bool unittest::userargs::failure_stop () const [virtual]
Returns whether to stop running after the first test fails.
Returns:
Whether to stop running after first failure
Definition at line 26 of file userargs.cpp.
References failure_stop_.
Referenced by unittest::make_default_environment(), and unittest::argparser::parse().
void unittest::userargs::failure_stop (bool value) [virtual]
Sets whether to stop running after first failure.
Parameters:
value The value
Definition at line 32 of file userargs.cpp.
References failure_stop_.
bool unittest::userargs::generate_xml () const [virtual]
Returns whether to generate XML output.
Returns:
Whether to generate XML output
Definition at line 38 of file userargs.cpp.
References generate_xml_.
Referenced by unittest::make_default_environment(), and unittest::argparser::parse().
void unittest::userargs::generate_xml (bool value) [virtual]
Sets whether to generate XML output.
Parameters:
value The value
Definition at line 44 of file userargs.cpp.
References generate_xml_.
std::string unittest::userargs::name_filter () const [virtual]
Returns a name filter on the full test name.
Returns:
The filter string
Definition at line 50 of file userargs.cpp.
References name_filter_.
Referenced by unittest::make_default_environment(), and unittest::argparser::parse().
void unittest::userargs::name_filter (const std::string & value) [virtual]
Sets a name filter on the full test name.
Parameters:
value The value
Definition at line 56 of file userargs.cpp.
References name_filter_.
std::string unittest::userargs::test_name () const [virtual]
Returns a certain test to be run. This supersedes the name filter.
Returns:
The test name
Definition at line 62 of file userargs.cpp.
References test_name_.
Referenced by unittest::make_default_environment(), and unittest::argparser::parse().
void unittest::userargs::test_name (const std::string & value) [virtual]
Sets a certain test to be run. This supersedes the name filter.
Parameters:
value The value
Definition at line 68 of file userargs.cpp.
References test_name_.
bool unittest::userargs::verbose () const [virtual]
Returns whether the output is verbose.
Returns:
Whether the output is verbose
Definition at line 14 of file userargs.cpp.
References verbose_.
Referenced by unittest::make_default_environment(), and unittest::argparser::parse().
void unittest::userargs::verbose (bool value) [virtual]
Sets whether the output is verbose.
Parameters:
value The value
Definition at line 20 of file userargs.cpp.
References verbose_.
std::string unittest::userargs::xml_filename () const [virtual]
Returns the XML output file name.
Returns:
The XML output file name
Definition at line 74 of file userargs.cpp.
References xml_filename_.
Referenced by unittest::make_default_environment(), and unittest::argparser::parse().
void unittest::userargs::xml_filename (const std::string & value) [virtual]
Sets the XML output file name.
Parameters:
value The value
Definition at line 80 of file userargs.cpp.
References xml_filename_.
Member Data Documentation
bool unittest::userargs::failure_stop_ [protected]
Definition at line 97 of file userargs.hpp.
Referenced by failure_stop().
bool unittest::userargs::generate_xml_ [protected]
Definition at line 98 of file userargs.hpp.
Referenced by generate_xml().
std::string unittest::userargs::name_filter_ [protected]
Definition at line 99 of file userargs.hpp.
Referenced by name_filter().
std::string unittest::userargs::test_name_ [protected]
Definition at line 100 of file userargs.hpp.
Referenced by test_name().
bool unittest::userargs::verbose_ [protected]
Definition at line 96 of file userargs.hpp.
Referenced by verbose().
std::string unittest::userargs::xml_filename_ [protected]
Definition at line 101 of file userargs.hpp.
Referenced by xml_filename().
The documentation for this class was generated from the following files:
userargs.hpp
userargs.cpp