libunittest: unittest::testsuite Class Reference
unittest::testsuite Class Reference
The test suite collecting test information (singleton, thread-safe)
#include <testsuite.hpp>
Public Member Functions
void set_verbose (bool verbose)
Sets whether output is verbose for running tests.
void set_failure_stop (bool failure_stop)
Sets whether to stop running after the first test fails.
void set_name_filter (const std::string &name_filter)
Sets a filter on the full test name. This will make the suite execute only those tests that begin with the given filter string.
void set_test_name (const std::string &test_name)
Sets a certain test to be run. This supersedes the name filter.
testresults get_results () const
Returns the accumulated test results.
Static Public Member Functions
static testsuite * instance ()
Returns a pointer to the instance of this class.
Private Member Functions
testsuite ()
testsuite (const testsuite &)
testsuite & operator= (const testsuite &)
void make_keep_running (const testlog &log)
void start_timing ()
void stop_timing ()
void collect (const testlog &log)
bool is_test_run (const std::string &class_name, const std::string &test_name) const
bool is_verbose () const
Friends
class testrunner
Detailed Description
The test suite collecting test information (singleton, thread-safe)
Definition at line 13 of file testsuite.hpp.
Constructor & Destructor Documentation
unittest::testsuite::testsuite () [private]
Definition at line 86 of file testsuite.cpp.
Referenced by instance().
unittest::testsuite::testsuite (const testsuite &) [private]
Member Function Documentation
void unittest::testsuite::collect (const testlog & log) [private]
Definition at line 155 of file testsuite.cpp.
References unittest::error, unittest::failure, unittest::pimplpattern< testsuite >::impl_, unittest::skipped, unittest::testlog::status, and unittest::success.
testresults unittest::testsuite::get_results () const
Returns the accumulated test results.
Returns:
The test results
Definition at line 123 of file testsuite.cpp.
References unittest::pimplpattern< testsuite >::impl_.
testsuite * unittest::testsuite::instance () [static]
Returns a pointer to the instance of this class.
Returns:
A pointer to the instance of this class
Definition at line 74 of file testsuite.cpp.
References testsuite().
Referenced by unittest::make_default_environment(), unittest::testrunner::testrunner(), and unittest::testrunner::~testrunner().
bool unittest::testsuite::is_test_run (const std::string & class_name, const std::string & test_name) const [private]
Definition at line 172 of file testsuite.cpp.
References unittest::pimplpattern< testsuite >::impl_, and unittest::is_test_executed().
bool unittest::testsuite::is_verbose () const [private]
Definition at line 184 of file testsuite.cpp.
References unittest::pimplpattern< testsuite >::impl_.
void unittest::testsuite::make_keep_running (const testlog & log) [private]
Definition at line 129 of file testsuite.cpp.
References unittest::pimplpattern< testsuite >::impl_, and unittest::testlog::successful.
testsuite& unittest::testsuite::operator= (const testsuite &) [private]
void unittest::testsuite::set_failure_stop (bool failure_stop)
Sets whether to stop running after the first test fails.
Parameters:
failure_stop Whether to stop running after first failure
Definition at line 99 of file testsuite.cpp.
References unittest::pimplpattern< testsuite >::impl_.
void unittest::testsuite::set_name_filter (const std::string & name_filter)
Sets a filter on the full test name. This will make the suite execute only those tests that begin with the given filter string.
Parameters:
name_filter The filter string
Definition at line 107 of file testsuite.cpp.
References unittest::pimplpattern< testsuite >::impl_.
void unittest::testsuite::set_test_name (const std::string & test_name)
Sets a certain test to be run. This supersedes the name filter.
Parameters:
test_name The test name
Definition at line 115 of file testsuite.cpp.
References unittest::pimplpattern< testsuite >::impl_.
void unittest::testsuite::set_verbose (bool verbose)
Sets whether output is verbose for running tests.
Parameters:
verbose Whether output is verbose for running tests
Definition at line 91 of file testsuite.cpp.
References unittest::pimplpattern< testsuite >::impl_.
void unittest::testsuite::start_timing () [private]
Definition at line 138 of file testsuite.cpp.
References unittest::pimplpattern< testsuite >::impl_.
void unittest::testsuite::stop_timing () [private]
Definition at line 147 of file testsuite.cpp.
References unittest::pimplpattern< testsuite >::impl_.
Friends And Related Function Documentation
friend class testrunner [friend]
Definition at line 54 of file testsuite.hpp.
The documentation for this class was generated from the following files:
testsuite.hpp
testsuite.cpp