libunittest: unittest::testrunner Class Reference
unittest::testrunner Class Reference
The test runner that is called by the testrun function. It executes and controls a test run.
#include <testrun.hpp>
Public Member Functions
testrunner (const std::string &class_name, const std::string &test_name)
Constructor.
~testrunner ()
Destructor.
bool is_executed ()
Returns whether to execute the current test.
template<typename TestCase >
void execute (TestCase &test, void(TestCase::*method)())
Executes the test method.
Private Attributes
testlog log_
Detailed Description
The test runner that is called by the testrun function. It executes and controls a test run.
Definition at line 17 of file testrun.hpp.
Constructor & Destructor Documentation
unittest::testrunner::testrunner (const std::string & class_name, const std::string & test_name)
Constructor.
Parameters:
class_name The name of the test class
test_name The name of the current test method
Definition at line 22 of file testrun.cpp.
References unittest::testlog::class_name, unittest::pimplpattern< testrunner >::impl_, unittest::testsuite::instance(), log_, unittest::testlog::test_name, and unittest::write_test_start_message().
unittest::testrunner::~testrunner ()
Destructor.
Definition at line 37 of file testrun.cpp.
References unittest::testlog::duration, unittest::duration_in_seconds(), unittest::pimplpattern< testrunner >::impl_, unittest::testsuite::instance(), log_, unittest::testlog::status, unittest::success, unittest::testlog::successful, and unittest::write_test_end_message().
Member Function Documentation
template<typename TestCase > void unittest::testrunner::execute (TestCase & test, void(TestCase::*)() method) [inline]
Executes the test method.
Parameters:
test An instance of a testcase class
method A test method belonging to the testcase class
Definition at line 43 of file testrun.hpp.
References unittest::error, unittest::testlog::error_type, unittest::failure, log_, unittest::testlog::message, unittest::testlog::status, and unittest::success.
Referenced by unittest::testrun().
bool unittest::testrunner::is_executed ()
Returns whether to execute the current test.
Returns:
Whether to execute the current test
Definition at line 52 of file testrun.cpp.
References unittest::pimplpattern< testrunner >::impl_.
Referenced by unittest::testrun().
Member Data Documentation
testlog unittest::testrunner::log_ [private]
Definition at line 67 of file testrun.hpp.
Referenced by execute(), testrunner(), and ~testrunner().
The documentation for this class was generated from the following files:
testrun.hpp
testrun.cpp