libunittest: unittest::formatting Class Reference
unittest::formatting Class Reference
A formatting interface.
#include <formatting.hpp>
Public Member Functions
formatting ()
Constructor.
virtual ~formatting ()
Destructor.
virtual std::string make_displayed_fail_message (const std::string &assertion, const std::string &text) const =0
A pure virtual method.
virtual int max_displayed_string_length () const =0
A pure virtual method.
virtual int max_displayed_value_precision () const =0
A pure virtual method.
template<typename T >
std::string str (const T &value) const
Converts a given value to string by taking into account the maximum string length and the maximum value precision.
Detailed Description
A formatting interface.
Definition at line 11 of file formatting.hpp.
Constructor & Destructor Documentation
unittest::formatting::formatting ()
Constructor.
Definition at line 5 of file formatting.cpp.
unittest::formatting::~formatting () [virtual]
Destructor.
Definition at line 8 of file formatting.cpp.
Member Function Documentation
virtual std::string unittest::formatting::make_displayed_fail_message (const std::string & assertion, const std::string & text) const [pure virtual]
A pure virtual method.
Parameters:
assertion The name of the assertion
text The assertion text
Returns:
A displayed fail message
Implemented in unittest::testcase< TestContext >.
Referenced by unittest::assertions::fail().
virtual int unittest::formatting::max_displayed_string_length () const [pure virtual]
A pure virtual method.
Returns:
The maximum displayed string length
Implemented in unittest::testcase< TestContext >.
Referenced by str().
virtual int unittest::formatting::max_displayed_value_precision () const [pure virtual]
A pure virtual method.
Returns:
The maximum displayed value precision
Implemented in unittest::testcase< TestContext >.
Referenced by str().
template<typename T > std::string unittest::formatting::str (const T & value) const [inline]
Converts a given value to string by taking into account the maximum string length and the maximum value precision.
Parameters:
value The value
Definition at line 50 of file formatting.hpp.
References max_displayed_string_length(), and max_displayed_value_precision().
Referenced by unittest::assertions::assert_approx_equal(), unittest::assertions::assert_approx_equal_containers(), unittest::assertions::assert_approx_in_container(), unittest::assertions::assert_approx_not_equal(), unittest::assertions::assert_approx_not_equal_containers(), unittest::assertions::assert_approx_not_in_container(), unittest::assertions::assert_equal(), unittest::assertions::assert_greater(), unittest::assertions::assert_greater_equal(), unittest::assertions::assert_in_container(), unittest::assertions::assert_in_range(), unittest::assertions::assert_not_equal(), unittest::assertions::assert_not_in_container(), unittest::assertions::assert_not_in_range(), unittest::assertions::assert_not_regex_match(), unittest::assertions::assert_regex_match(), unittest::assertions::assert_smaller(), and unittest::assertions::assert_smaller_equal().
The documentation for this class was generated from the following files:
formatting.hpp
formatting.cpp