libunittest: unittest Namespace Reference
unittest Namespace Reference
Unit testing in C++.
Classes
struct implementation< argparser >
struct implementation< testrunner >
struct implementation< testsuite >
class argparser
An argument parser.
class argparser_error
The exception class to indicate argument errors.
class assertions
A collection of assertions.
class formatting
A formatting interface.
class pimplpattern
A class defining the private implementation pattern.
class nocontext
A placeholder for the absent of a test context.
class testcase
The class from which to derive when implementing a test case. The test context is optional.
class testfailure
The exception class to indicate test failures.
struct testlog
Stores logging info about a single test.
struct testresults
Stores the test results.
class testrunner
The test runner that is called by the testrun function. It executes and controls a test run.
class testsuite
The test suite collecting test information (singleton, thread-safe)
class userargs
High level user arguments to control application behavior.
Enumerations
enum teststatus { success = 0, failure = 1, error = 2, skipped = 3 }
An enumeration for the test status.
Functions
int make_default_environment (int argc, char **argv)
Sets up a default testing environment and calls run_all_tests(). This high-level function is intended to be used directly from the user's main() function.
void write_test_start_message (std::ostream &stream, const testlog &log, bool verbose)
Writes a test start message to the given output stream.
void write_test_end_message (std::ostream &stream, const testlog &log, bool verbose)
Writes a test end message to the given output stream.
void write_xml (std::ostream &stream, const testresults &results, const std::chrono::system_clock::time_point &time_point=std::chrono::system_clock::now())
Writes the test results as an XML to the given output stream.
void write_summary (std::ostream &stream, const testresults &results)
Writes the test summary to the given output stream.
void write_error_info (std::ostream &stream, const testresults &results)
Writes the error info to the given output stream.
bool is_test_executed (const std::string &test_name, const std::string &exact_name, const std::string &filter_name)
Returns whether a given test is executed.
void write_to_stream (std::ostream &stream)
An overload doing nothing to finish template recursion.
void write_horizontal_bar (std::ostream &stream, char character, int length=50)
Writes a horizontal bar to the given output stream.
double duration_in_seconds (const std::chrono::duration< double > &duration)
Casts a duration value to seconds.
bool is_regex_matched (const std::string &value, const std::string &regex)
Checks if a value matches a regular expression.
bool is_regex_matched (const std::string &value, const std::regex &regex)
Checks if a value matches a regular expression.
std::string xml_escape (const std::string &data)
Escapes a string for use in an XML document.
std::string make_iso_timestamp (const std::chrono::system_clock::time_point &time_point)
Generates the ISO8601 time stamp from a time point object.
std::tuple< int, int, int > get_version_tuple ()
Returns the libunittest version as a tuple.
std::string get_version_string ()
Returns the libunittest version as a string.
template<typename TestCase >
void call ()
Calls the static run() method of the test class.
template<typename TestCase , typename TestContext >
void call (const TestContext &context)
Calls the static run() method of the test class with the test context as the one parameter.
void run_all_tests ()
This function is to be implemented by the user if any of the predefined environment functions are called. run_all_tests() should contain a list of calls to test classes.
template<typename TestCase >
void testrun (void(TestCase::*method)(), const std::string &class_name, const std::string &test_name)
A test run (thread-safe)
template<typename TestContext , typename TestCase >
void testrun (TestContext &context, void(TestCase::*method)(), const std::string &class_name, const std::string &test_name)
A test run with a test context (thread-safe)
template<typename T , typename... Args>
void write_to_stream (std::ostream &stream, const T &arg, const Args &...args)
Writes arguments to an output stream via template recursion.
template<typename T , typename... Args>
std::string join (const T &arg, const Args &...args)
Joins an arbitrary number of input arguments to a single string. All arguments must implement the << operator.
template<typename T , typename U , typename V >
bool is_approx_equal (const T &first, const U &second, const V &eps)
Checks if two values are equal up to some epsilon.
template<typename InputIterator1 , typename InputIterator2 , typename T >
bool is_approx_equal (InputIterator1 first1, InputIterator1 last1, InputIterator2 first2, const T &eps)
Checks whether the elements in two ranges are approx. equal up to some epsilon.
template<typename T , typename U , typename V >
bool is_in_range (const T &value, const U &lower, const V &upper)
Checks if a value is in a given range. The bounds are excluding.
template<typename T , typename Container >
bool is_contained (const T &value, const Container &container)
Checks if a value is in a container.
template<typename T , typename Container , typename U >
bool is_approx_contained (const T &value, const Container &container, const U &eps)
Checks if a value is approx. in a container up to some epsilon.
template<typename Container1 , typename Container2 >
bool is_containers_equal (const Container1 &first, const Container2 &second)
Checks if two containers are equal.
template<typename Container1 , typename Container2 , typename V >
bool is_containers_approx_equal (const Container1 &first, const Container2 &second, const V &eps)
Checks if two containers are approx. equal up to some epsilon.
Detailed Description
Unit testing in C++.
Enumeration Type Documentation
enum unittest::teststatus
An enumeration for the test status.
Enumerator:
success
failure
error
skipped
Definition at line 9 of file teststatus.hpp.
Function Documentation
template<typename TestCase > void unittest::call ()
Calls the static run() method of the test class.
Definition at line 11 of file call.hpp.
template<typename TestCase , typename TestContext > void unittest::call (const TestContext & context)
Calls the static run() method of the test class with the test context as the one parameter.
Parameters:
context The test context
Definition at line 23 of file call.hpp.
double unittest::duration_in_seconds (const std::chrono::duration< double > & duration)
Casts a duration value to seconds.
Parameters:
duration The duration value
Returns:
The duration in seconds
Definition at line 19 of file utilities.cpp.
Referenced by unittest::implementation< testsuite >::get_duration(), and unittest::testrunner::~testrunner().
std::string unittest::get_version_string ()
Returns the libunittest version as a string.
Returns:
The version as a string
Definition at line 13 of file version.cpp.
References get_version_tuple(), and join().
Referenced by unittest::implementation< argparser >::write_help().
std::tuple< int, int, int > unittest::get_version_tuple ()
Returns the libunittest version as a tuple.
Returns:
The version as a tuple
Definition at line 7 of file version.cpp.
Referenced by get_version_string().
template<typename T , typename Container , typename U > bool unittest::is_approx_contained (const T & value, const Container & container, const U & eps)
Checks if a value is approx. in a container up to some epsilon.
Parameters:
value A value
container A container
eps The epsilon
Returns:
Whether the value is approx. in the container
Definition at line 174 of file utilities.hpp.
References is_approx_equal().
Referenced by unittest::assertions::assert_approx_in_container(), and unittest::assertions::assert_approx_not_in_container().
template<typename T , typename U , typename V > bool unittest::is_approx_equal (const T & first, const U & second, const V & eps)
Checks if two values are equal up to some epsilon.
Parameters:
first A value
second Another value
eps The epsilon
Returns:
Whether the values are equal up to some epsilon
Definition at line 92 of file utilities.hpp.
Referenced by unittest::assertions::assert_approx_equal(), unittest::assertions::assert_approx_not_equal(), is_approx_contained(), is_approx_equal(), and is_containers_approx_equal().
template<typename InputIterator1 , typename InputIterator2 , typename T > bool unittest::is_approx_equal (InputIterator1 first1, InputIterator1 last1, InputIterator2 first2, const T & eps)
Checks whether the elements in two ranges are approx. equal up to some epsilon.
Parameters:
first1 An input iterator
last1 An input iterator
first2 An input iterator
eps The epsilon
Returns:
Whether the elements in the two ranges are approx. equal
Definition at line 116 of file utilities.hpp.
References is_approx_equal().
template<typename T , typename Container > bool unittest::is_contained (const T & value, const Container & container)
Checks if a value is in a container.
Parameters:
value A value
container A container
Returns:
Whether the value is in the container
Definition at line 155 of file utilities.hpp.
Referenced by unittest::assertions::assert_in_container(), and unittest::assertions::assert_not_in_container().
template<typename Container1 , typename Container2 , typename V > bool unittest::is_containers_approx_equal (const Container1 & first, const Container2 & second, const V & eps)
Checks if two containers are approx. equal up to some epsilon.
Parameters:
first A container
second Another container
eps The epsilon
Returns:
Whether the two containers are approx. equal
Definition at line 218 of file utilities.hpp.
References is_approx_equal().
Referenced by unittest::assertions::assert_approx_equal_containers(), and unittest::assertions::assert_approx_not_equal_containers().
template<typename Container1 , typename Container2 > bool unittest::is_containers_equal (const Container1 & first, const Container2 & second)
Checks if two containers are equal.
Parameters:
first A container
second Another container
Returns:
Whether the containers are equal
Definition at line 195 of file utilities.hpp.
Referenced by unittest::assertions::assert_equal_containers(), and unittest::assertions::assert_not_equal_containers().
template<typename T , typename U , typename V > bool unittest::is_in_range (const T & value, const U & lower, const V & upper)
Checks if a value is in a given range. The bounds are excluding.
Parameters:
value A value
lower The lower bound
upper The upper bound
Returns:
Whether the value is in a given range
Definition at line 140 of file utilities.hpp.
Referenced by unittest::assertions::assert_in_range(), and unittest::assertions::assert_not_in_range().
bool unittest::is_regex_matched (const std::string & value, const std::string & regex)
Checks if a value matches a regular expression.
Parameters:
value A value
regex A regular expression
Returns:
Whether a value matches the regular expression
Definition at line 25 of file utilities.cpp.
Referenced by unittest::assertions::assert_not_regex_match(), and unittest::assertions::assert_regex_match().
bool unittest::is_regex_matched (const std::string & value, const std::regex & regex)
Checks if a value matches a regular expression.
Parameters:
value A value
regex A regular expression
Returns:
Whether a value matches the regular expression
Definition at line 32 of file utilities.cpp.
bool unittest::is_test_executed (const std::string & test_name, const std::string & exact_name, const std::string & filter_name)
Returns whether a given test is executed.
Parameters:
test_name The full test name
exact_name An exact name to be checked for, ignored if empty
filter_name A filter for the beginning of the test name, ignored if empty
Returns:
Whether a given test is executed
Definition at line 190 of file testsuite.cpp.
Referenced by unittest::testsuite::is_test_run().
template<typename T , typename... Args> std::string unittest::join (const T & arg, const Args &... args)
Joins an arbitrary number of input arguments to a single string. All arguments must implement the << operator.
Parameters:
arg An argument
args An arbitrary number of arguments, can be omitted
Returns:
The joined string
Definition at line 56 of file utilities.hpp.
References write_to_stream().
Referenced by unittest::assertions::assert_no_throw(), unittest::assertions::assert_throw(), unittest::assertions::fail(), get_version_string(), unittest::implementation< argparser >::help_and_throw(), unittest::testcase< TestContext >::make_displayed_fail_message(), and unittest::argparser::parse().
int unittest::make_default_environment (int argc, char ** argv)
Sets up a default testing environment and calls run_all_tests(). This high-level function is intended to be used directly from the user's main() function.
Parameters:
argc The number of user arguments
argv The array of user arguments
Returns:
A platform dependent program execution status: A success value if all tests succeed and an error value otherwise
Definition at line 11 of file environments.cpp.
References unittest::userargs::failure_stop(), unittest::userargs::generate_xml(), unittest::testsuite::instance(), unittest::userargs::name_filter(), unittest::argparser::parse(), run_all_tests(), unittest::userargs::test_name(), unittest::userargs::verbose(), write_error_info(), write_summary(), write_xml(), and unittest::userargs::xml_filename().
std::string unittest::make_iso_timestamp (const std::chrono::system_clock::time_point & time_point)
Generates the ISO8601 time stamp from a time point object.
Parameters:
time_point The time point object
Returns:
The ISO8601 time stamp (e.g. 2013-06-29T14:12:05)
Definition at line 57 of file utilities.cpp.
Referenced by write_xml().
void unittest::run_all_tests ()
This function is to be implemented by the user if any of the predefined environment functions are called. run_all_tests() should contain a list of calls to test classes.
Referenced by make_default_environment().
template<typename TestCase > void unittest::testrun (void(TestCase::*)() method, const std::string & class_name, const std::string & test_name)
A test run (thread-safe)
Parameters:
method A pointer to the method to be run
class_name The name of the test class
test_name The name of the current test method
Definition at line 78 of file testrun.hpp.
References unittest::testrunner::execute(), and unittest::testrunner::is_executed().
template<typename TestContext , typename TestCase > void unittest::testrun (TestContext & context, void(TestCase::*)() method, const std::string & class_name, const std::string & test_name)
A test run with a test context (thread-safe)
Parameters:
context The test context
method A pointer to the method to be run
class_name The name of the test class
test_name The name of the current test method
Definition at line 100 of file testrun.hpp.
References unittest::testrunner::execute(), and unittest::testrunner::is_executed().
void unittest::write_error_info (std::ostream & stream, const testresults & results)
Writes the error info to the given output stream.
Parameters:
stream The output stream
results The test results
Definition at line 82 of file testresults.cpp.
References error, failure, unittest::testresults::successful, unittest::testresults::testlogs, and write_horizontal_bar().
Referenced by make_default_environment().
void unittest::write_horizontal_bar (std::ostream & stream, char character, int length = 50)
Writes a horizontal bar to the given output stream.
Parameters:
stream The output stream
character The character to repeat
length The length of the bar
Definition at line 10 of file utilities.cpp.
Referenced by write_error_info(), and write_summary().
void unittest::write_summary (std::ostream & stream, const testresults & results)
Writes the test summary to the given output stream.
Parameters:
stream The output stream
results The test results
Definition at line 56 of file testresults.cpp.
References unittest::testresults::duration, unittest::testresults::n_errors, unittest::testresults::n_failures, unittest::testresults::n_successes, unittest::testresults::n_tests, and write_horizontal_bar().
Referenced by make_default_environment().
void unittest::write_test_end_message (std::ostream & stream, const testlog & log, bool verbose)
Writes a test end message to the given output stream.
Parameters:
stream The output stream
log A test log
verbose Whether to use verbose output
Definition at line 23 of file testlog.cpp.
References error, failure, skipped, unittest::testlog::status, and success.
Referenced by unittest::testrunner::~testrunner().
void unittest::write_test_start_message (std::ostream & stream, const testlog & log, bool verbose)
Writes a test start message to the given output stream.
Parameters:
stream The output stream
log A test log
verbose Whether to use verbose output
Definition at line 12 of file testlog.cpp.
References unittest::testlog::class_name, and unittest::testlog::test_name.
Referenced by unittest::testrunner::testrunner().
void unittest::write_to_stream (std::ostream & stream)
An overload doing nothing to finish template recursion.
Parameters:
stream An output stream
Definition at line 6 of file utilities.cpp.
Referenced by join(), and write_to_stream().
template<typename T , typename... Args> void unittest::write_to_stream (std::ostream & stream, const T & arg, const Args &... args)
Writes arguments to an output stream via template recursion.
Parameters:
stream An output stream
arg An argument
args An arbitrary number of arguments
Definition at line 39 of file utilities.hpp.
References write_to_stream().
void unittest::write_xml (std::ostream & stream, const testresults & results, const std::chrono::system_clock::time_point & time_point = std::chrono::system_clock::now())
Writes the test results as an XML to the given output stream.
Parameters:
stream The output stream
results The test results
time_point The time point used in the root tag (defaults to now)
Definition at line 13 of file testresults.cpp.
References unittest::testresults::duration, failure, make_iso_timestamp(), unittest::testresults::n_errors, unittest::testresults::n_failures, unittest::testresults::n_skipped, unittest::testresults::n_tests, unittest::testresults::testlogs, and xml_escape().
Referenced by make_default_environment().
std::string unittest::xml_escape (const std::string & data)
Escapes a string for use in an XML document.
Parameters:
data Some string
Definition at line 39 of file utilities.cpp.
Referenced by write_xml().